# Generated by Django 4.1.3 on 2022-11-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='DateOfJoining',
            field=models.CharField(max_length=500),
        ),
    ]
